### ISSUE TITLE
Windows 10 - run-script build fails with error

### ISSUE THREAD

**Issue by mjosborne1** [FHIR/fhir.js#79]
I guess my main concern is that this code may not be supported on Windows 10. If it is not supported, this needs to be made clear in the documentation so that Windows users do not waste time trying to install it.

This line fails when I try to run the build command on my Windows 10 machine :
rm -rf dist && `npm bin`/webpack --progress --colors && `npm bin`/coffee --output lib --compile src
D:\Code\fhir.js>npm run-script build

The full trace is shown below:
npm@3.6.0 C:\Users\Michael\AppData\Roaming\npm\node_modules\npm

D:\Code\fhir.js>
D:\Code\fhir.js>npm run-script build

> fhir.js@0.0.0 build D:\Code\fhir.js
> rm -rf dist && `npm bin`/webpack --progress --colors && `npm bin`/coffee --output lib --compile src

'`npm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
npm ERR! node v4.5.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! fhir.js@0.0.0 build: `rm -rf dist && `npm bin`/webpack --progress --colors && `npm bin`/coffee --output lib --compile src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fhir.js@0.0.0 build script 'rm -rf dist && `npm bin`/webpack --progress --colors && `npm bin`/coffee --output lib --compile src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fhir.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf dist && `npm bin`/webpack --progress --colors && `npm bin`/coffee --output lib --compile src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fhir.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fhir.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Code\fhir.js\npm-debug.log

See also the npm debug log attachment

[npm-debug.log.txt](https://github.com/FHIR/fhir.js/files/458676/npm-debug.log.txt)

Note:
Contrary to the error message, npm _is_ installed on my system:

D:\Code\fhir.js>npm /?

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install,
    install-test, issues, it, la, link, list, ll, ln, login,
    logout, ls, outdated, owner, pack, ping, prefix, prune,
    publish, r, rb, rebuild, remove, repo, restart, rm, root,
    run-script, s, se, search, set, show, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unlink, unpublish, unstar, up, update, upgrade, v, verison,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Michael\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.6.0 C:\Users\Michael\AppData\Roaming\npm\node_modules\npm

**Comment by Dunmail** [comment]
Package.json that can be used to define any OS pre-reqs:
https://docs.npmjs.com/files/package.json#os

--
Dr Dunmail Hodkinson
Chief Technology Officer at Black Pear Software Ltd

dunmail@blackpear.com | +44 (0)1434 674396 | +44 (0)7787 410589 | skype:
dunmail.hodkinson
www.blackpear.com

This E-mail is confidential and may also be privileged. It must not be
disclosed to any other person or party without the prior authority of
Black Pear Software Limited. To do so may be unlawful. If you are not
the intended recipient of this, please notify us immediately and delete
the e-mail received.

This e-mail and any attached files have been checked for viruses.
Although we employ virus protection software, we cannot accept any
responsibility for any loss or damage to your systems due to viruses or
malicious code not detected.

Any views or opinions contained within this message are solely those of
the author and do not necessarily represent those of Black Pear
Software Limited.



On Wed, Sep 7, 2016, at 09:54 AM, Michael Osborne wrote:
> I guess my main concern is that this code is not supported on Windows
> 10. If it is not supported, this nees to be made clear in the
> documentation so that Windows users do not waste time trying to
> install it.
> This line fails when I try to run the build command on my Windows 10
> machine :
>  rm -rf dist && npm bin/webpack --progress --colors && npm bin/coffee
>  --output lib --compile src
>  D:\Code\fhir.js>npm run-script build
> The full trace is shown below:
>  npm@3.6.0 C:\Users\Michael\AppData\Roaming\npm\node_modules\npm
> D:\Code\fhir.js>
>  D:\Code\fhir.js>npm run-script build
>> fhir.js@0.0.0 build D:\Code\fhir.js
>>  rm -rf dist && npm bin/webpack --progress --colors && npm bin/coffee
>>  --output lib --compile src
> '`npm' is not recognized as an internal or external command,
>  operable program or batch file.
> npm ERR! Windows_NT 10.0.14393
>  npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\bin\npm-
>  cli.js" "run-script" "build"
>  npm ERR! node v4.5.0
>  npm ERR! npm  v3.6.0
>  npm ERR! code ELIFECYCLE
>  npm ERR! fhir.js@0.0.0 build: rm -rf dist &&npm bin/webpack --
>  progress --colors &&npm bin/coffee --output lib --compile src
>  npm ERR! Exit status 1
>  npm ERR!
>  npm ERR! Failed at the fhir.js@0.0.0 build script 'rm -rf dist && npm
>  bin/webpack --progress --colors && npm bin/coffee --output lib --
>  compile src'.
>  npm ERR! Make sure you have the latest version of node.js and npm
>  installed.
>  npm ERR! If you do, this is most likely a problem with the fhir.js
>  package,
>  npm ERR! not with npm itself.
>  npm ERR! Tell the author that this fails on your system:
>  npm ERR!     rm -rf dist && npm bin/webpack --progress --colors &&
>  npm bin/coffee --output lib --compile src
>  npm ERR! You can get information on how to open an issue for this
>  project with:
>  npm ERR!     npm bugs fhir.js
>  npm ERR! Or if that isn't available, you can get their info via:
>  npm ERR!     npm owner ls fhir.js
>  npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
>  npm ERR!     D:\Code\fhir.js\npm-debug.log
> See also the npm debug log attachment
> npm-debug.log.txt[1]
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].
>


Links:

  1. https://github.com/FHIR/fhir.js/files/458676/npm-debug.log.txt
  2. https://github.com/FHIR/fhir.js/issues/79

**Comment by mjosborne1** [comment]
Thanks - but I could not see any os limitations in the package.json.
Can you please confirm this is true?
BTW....My node version is up-to-date
D:\Code\fhir.js>node -v
v4.5.0

**Comment by mjosborne1** [comment]
Interesting...When I run this under the Linux Subsystem for windows, I get a similar error:


michael@METABOX-MIKE:~/code/fhir.js$ npm run-script build

> fhir.js@0.0.0 build /home/michael/code/fhir.js
> rm -rf dist && `npm bin`/webpack --progress --colors && `npm bin`/coffee --output lib --compile src

npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
michael@METABOX-MIKE:~/code/fhir.js$

**Comment by Dunmail** [comment]
Just highlighting that if package doesn't run on Windows, there is a
mechanism in npm to flag this.

--
Dr Dunmail Hodkinson
Chief Technology Officer at Black Pear Software Ltd

dunmail@blackpear.com | +44 (0)1434 674396 | +44 (0)7787 410589 | skype:
dunmail.hodkinson
www.blackpear.com

This E-mail is confidential and may also be privileged. It must not be
disclosed to any other person or party without the prior authority of
Black Pear Software Limited. To do so may be unlawful. If you are not
the intended recipient of this, please notify us immediately and delete
the e-mail received.

This e-mail and any attached files have been checked for viruses.
Although we employ virus protection software, we cannot accept any
responsibility for any loss or damage to your systems due to viruses or
malicious code not detected.

Any views or opinions contained within this message are solely those of
the author and do not necessarily represent those of Black Pear
Software Limited.



On Wed, Sep 7, 2016, at 10:04 AM, Michael Osborne wrote:
> Thanks - but I could not see any os limitations in the package.json.
>  Can you please confirm this is true?
>  BTW....My node version is up-to-date
>  D:\Code\fhir.js>node -v
>  v4.5.0
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/FHIR/fhir.js/issues/79#issuecomment-245220156

**Comment by StefH** [comment]
Fixed in https://github.com/FHIR/fhir.js/pull/80

**Comment by mjosborne1** [comment]
Thanks for fixing this - the build script runs now and all tests pass.
